'use strict';
/* eslint-disable */

const data = [
  {
    'id': 'item-1',
    'title': 'Playzee',
    'flag': 'player favourite',
    'logoURL': 'https://www.playzee.com/images/logo-small.svg',
    'logoBg': '#a100c9',
    'bonus1': '100% Up to',
    'bonus2': '1500',
    'bonus3': '+ 150 Zee Spins',
    'bonus4': '+ 500 Zee Points',
    'bonus5': '',
    'userRating': '2589',
    'rating': '10.0',
  },
  {
    'id': 'item-2',
    'title': 'Machance',
    'flag': 'trending',
    'logoURL': 'https://www.machancecasino.com/templates/machance/images/logo_mc_origin.svg',
    'logoBg': '#000',
    'bonus1': '200% Up to',
    'bonus2': '500',
    'bonus3': '+ 20 FREE SPINS',
    'bonus4': '',
    'bonus5': '',
    'userRating': '2063',
    'rating': '9.9',
  },
  {
    'id': 'item-3',
    'title': 'Intense',
    'flag': 'number 1 in europe',
    'logoURL': 'https://pic2.casinointense.com/templates/intense/images/logo.png',
    'logoBg': '#d6e3e2',
    'bonus1': '200% Up to',
    'bonus2': '3,000',
    'bonus3': '+ 30 FREE SPINS',
    'bonus4': '',
    'bonus5': '',
    'userRating': '1975',
    'rating': '9.8',
  },
  {
    'id': 'item-4',
    'title': 'LeoVegas',
    'flag': 'exclusive',
    'logoURL': 'https://cdn.leovegas.com/fulcrum/v3/master/static/2e7c1afd1dae294fcdc3dadd6792e204.svg',
    'logoBg': '#00b2ae',
    'bonus1': '100% Up to',
    'bonus2': '200',
    'bonus3': '+ 25 Free Spins on Book of Dead',
    'bonus4': '',
    'bonus5': '',
    'userRating': '1890',
    'rating': '9.4',
  },
  {
    'id': 'item-5',
    'title': 'Casumo',
    'flag': '',
    'logoURL': 'https://onlinecasinos77sweden.com/img/casinologo/Casumo.png',
    'logoBg': '#d6e3e2',
    'bonus1': 'Welcome Bonus',
    'bonus2': '250',
    'bonus3': '+ 20 Free Spins',
    'bonus4': '',
    'bonus5': '',
    'userRating': '1816',
    'rating': '9.3',
  },
];

module.exports = { data };
